### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by Be-ing** [Futsch1/image-sieve#34]
Using Breeze Dark on KDE
![image](https://user-images.githubusercontent.com/9455094/153922429-ff98ad69-896f-4ce1-b4d2-f43e2e023e47.png)
Consider using [dark-light](https://lib.rs/crates/dark-light)

**Comment by Futsch1** [comment]
Great suggestion for adding a dark theme!

However, I just pushed a commit that forces the slint-ui "fluent" style, which will result in a uniform look independent if Qt is installed or not (see [https://github.com/slint-ui/slint/discussions/949](https://github.com/slint-ui/slint/discussions/949)). This should fix this behavior as well, however, I'll keep the issue as an enhancement request for a dark theme.
